### ISSUE TITLE
Código CREATE TABLE no funciona en Sql Server 2008

### ISSUE THREAD

**Issue by ekz4** [knxroot/bdcut-cl#14]
En este código, en las líneas para crear tabla provincia y tabla comuna, tuve que agregar un paréntesis de cierre extra al final. Observen el final de la primera sentencia y luego las 2 siguientes.

CREATE TABLE region(REGION_ID int NOT NULL DEFAULT '0', REGION_NOMBRE varchar(50) DEFAULT NULL,PRIMARY KEY (REGION_ID) );
CREATE TABLE provincia (PROVINCIA_ID int NOT NULL DEFAULT '0', PROVINCIA_NOMBRE varchar(23) DEFAULT NULL, PRIMARY KEY (PROVINCIA_ID), PROVINCIA_REGION_ID int FOREIGN KEY REFERENCES region(REGION_ID);
CREATE TABLE comuna (COMUNA_ID int NOT NULL DEFAULT '0', COMUNA_NOMBRE varchar(20) DEFAULT NULL, COMUNA_PROVINCIA_ID int FOREIGN KEY REFERENCES provincia (PROVINCIA_ID), PRIMARY KEY (COMUNA_ID);

**Comment by Aterbonus** [comment]
Efectivamente al [json de Sql Server](https://github.com/knxroot/bdcut-cl/blob/master/SCRIPT/formatos/sqlserver.json#L32-L33) en que se basa el script le faltan los paréntesis de cierre.

**Comment by dalacost** [comment]
se agregaron los ")" faltantes.
