### ISSUE TITLE
XVI Región de Ñuble

### ISSUE THREAD

**Issue by dalacost** [knxroot/bdcut-cl#4]
Existe una nueva región. 

http://www.gob.cl/2015/08/20/mandataria-firma-proyecto-de-ley-que-crea-la-region-de-nuble/

**Comment by knxroot** [comment]
Según boletín 10277-06 que puede ser consultado en http://www.senado.cl/appsenado/templates/tramitacion/index.php el proyecto se encontraría aún en tramitación. Cuando pase a estado finalizado lo agregamos al proyecto actual. 

Comenzaré a preparar los cambios de acuerdo a lo descrito en el archivo descargable del mensaje del proyecto disponible en la pág. del senado.

**Comment by knxroot** [comment]
Abrí la rama "proyecto-ley-region-nuble" donde propuse el cambio de acuerdo a lo que se comenta en la propuesta de ley ver commit: cdcac84579644ee5f13096dfa865f28f8a841681 .

Los códigos de las comunas reagrupadas en las nuevas provincias no se modificaron, aunque creo que en el supuesto de que se apruebe cuando el ministerio del interior publique en le diario oficial los nuevos códigos territoriales probablemente modifique los códigos de las comunas involucradas como ya lo hizo anteriormente en el Decreto Exento Nº 910, del Ministerio del Interior, publicado en el Diario Oficial del 14 de Junio de 2007 según se puede apreciar en las referencias de http://www.sinim.cl/archivos/centro_descargas/modificacion_instructivo_pres_codigos.pdf . 

Creo que lo más sano sería entonces esperar llegar a la instancia luego de la aprobación del proyecto de ley y ver cómo plantea los códigos el ministerio. La rama "master" de repositorio debe seguir de momento adelante sin considerar este cambio hasta que sea realmente oficial luego hacemos un merge de ambas ramas.

**Comment by knxroot** [comment]
![nueva_propuesta](http://static.latercera.com/20150711/2149356.jpg)

**Comment by knxroot** [comment]
Preparativos continúan en la rama [proyecto-ley-region-nuble](https://github.com/knxroot/bdcut-cl/branches), re abrir el issue cuando aprueben el proyecto de ley.

**Comment by dalacost** [comment]
este proyecto ya estaría en su ultima etapa en el senado
http://www.senado.cl/appsenado/index.php?mo=tramitacion&ac=tramites&proyid=10691&=camara=Sboletin=10277-06&etc=1482415766715

**Comment by dalacost** [comment]
Reactivo esto, hoy se firmó el decreto para esta nueva región y posible entraría en vigencia en sept. 2018. 
http://www.latercera.com/noticia/firma-bachelet-hoy-nace-region-nuble/

@knxroot tu revisas esto? ya que tienes lista la propuesta en tu rama.

**Comment by knxroot** [comment]
Aca deje el cambio ok en el CSV, pero falta correjir las otras fuentes antes de fusionar con master. Notar que este csv es correcto por lo que puede tomarse como línea base https://github.com/knxroot/bdcut-cl/commit/857d2c5c3505c26b89beedbce09326df2aa1b788 .  (Trabajo futuro línea base debe ser CSV resto de fuentes deberían autogenerarse basada en algún script)

**Comment by dalacost** [comment]
Se agregó un release 0.3 beta que contiene los cambios de ñuble
https://github.com/knxroot/bdcut-cl/tree/v0.3-beta

**Comment by dalacost** [comment]
Aqui se incorporaron los cambios finales https://github.com/knxroot/bdcut-cl/commit/39da9524db8156c3deeba0067d9f4119f48eb7a9
