### ISSUE TITLE
ISO 3166-2:CL

### ISSUE THREAD

**Issue by dalacost** [knxroot/bdcut-cl#5]
La gente de OpenStreetMap Chile me avisó de esto. Aunque nunca he visto que se use en la vida real de Chile, quizá debería ser bueno agregarlo también. 

https://es.wikipedia.org/wiki/ISO_3166-2:CL

**Comment by knxroot** [comment]
Se ve interesante pero es sólo para Regiones?, en el caso de provincias y comunas existe algo similar?. Si encuentras más ISOs relacionadas a los códigos que se le pueden asociar a las comunas, regiones, provincias sería ideal listarlos acá ya que el sistema de códigos únicos territoriales es bastante oscuro y se desconocen las reglas de fondo que aplican a la hora de asignar un código, quizás sería bueno migrar a una asignación propia o más globalizada.

**Comment by dalacost** [comment]
Tal parece que en este caso llega solo hasta el primer nivel de división. 
Por otro lado encontré esto: https://en.wikipedia.org/wiki/List_of_FIPS_region_codes_(A%E2%80%93C)#CI:_Chile , pero parece que los códigos de Chile están mal, pues se saltaron algunos números. Intenté buscar la info oficial sin resultados.

**Comment by dalacost** [comment]
en el commit https://github.com/knxroot/bdcut-cl/commit/47e8b21b6f82f49f6b3a4b797e685e1ef1b83c07 Se agrega soporte para ISO_3166-2:CL según documento oficial http://web.archive.org/web/20110606085707/http://www.iso.org/iso/iso_3166-2_newsletter_ii-2_2010-06-30.pdf Pagina 17

**Comment by knxroot** [comment]
Mira este: [ihasc](http://www.statoids.com/ihasc.html) para [regiones](http://www.statoids.com/ucl.html) y [provincias] (http://www.statoids.com/ycl.html). Se trata de una propuesta no oficial pero interesante ya que baja a nivel de provincias.  Agregué estos links a REFERENCES.md
