### ISSUE TITLE
Inconsistencia en nombres de regiones

### ISSUE THREAD

**Issue by Aterbonus** [knxroot/bdcut-cl#6]
En los nombres de regiones tenemos:

1. Tarapacá
2. Antofagasta
3. Atacama
4. Coquimbo
5. Valparaíso
6. Región del Libertador Gral. Bernardo O’Higgins
7. Región del Maule
8. Región del Biobío
9. Región de la Araucanía
10. Región de Los Lagos
11. Región Aisén del Gral. Carlos Ibáñez del Campo
12. Región de Magallanes y de la Antártica Chilena
13. Región Metropolitana de Santiago
14. Región de Los Ríos
15. Arica y Parinacota

¿Hay alguna razón por lo que las regiones de Tarapacá, Antofagasta, Atacama, Coquimbo, Valparaíso y Arica y Parinacota no les enteceda la palabra "Región"?

**Comment by knxroot** [comment]
Ver Lectura obligatoria en https://github.com/knxroot/bdcut-cl/blob/master/REFERENCES.md , si te das cuenta el texto llega desde allí sin alteraciones. De todas formas creo que tienes razón la verdad no tiene sentido que tenga formatos diferentes, vamos a modificar los archivos aunque no quede idéntico al documento oficial.

**Comment by dalacost** [comment]
Yo voto por dejar el oficial. (aunque igual feo que el estado ponga mal los nombres), luego cada desarrollador puede editarlos. Deberíamos dejar una advertencia en el manual.

**Comment by knxroot** [comment]
No he tenido tiempo de metrrme en esto dale no mas edita el proyecto

**Comment by dalacost** [comment]
Lo más rápido es dejar un warning o una descripción en la portada para reflejar la duda de  @Aterbonus . Eso haré.

**Comment by dalacost** [comment]
Para cerrar este issue dejé una nota en la sección de avisos del readme principal, haciendo referencia también a pasar por la lectura del references.md ( commit: https://github.com/knxroot/bdcut-cl/commit/9f3a5413f94ecd2ae3b466d43bb4d38c78637de8 ). Doy por cerrado este caso.
