### ISSUE TITLE
Insert BDCUT_CL__PosgreSQL_utf8 no funciona

### ISSUE THREAD

**Issue by mbalmaceda** [knxroot/bdcut-cl#8]
ERROR:  error de sintaxis en o cerca de «1101»
LINE 81: 1101 Iquique 11
         ^
********** Error **********

ERROR: error de sintaxis en o cerca de «1101»
SQL state: 42601
Character: 2188

**Comment by dalacost** [comment]
se debe importar desde la terminal. actualizaré la doc. saludos.

**Comment by dalacost** [comment]
revisar doc oficial.  https://github.com/knxroot/bdcut-cl/tree/master/BD/PosgreSQL_utf8

**Comment by mbalmaceda** [comment]
Bakan, muchas gracias por su aporte, esta realmente bueno, saludos !
